# Model Configuration for trenddit-flow
# This file contains model IDs for various AI providers used in agent framework comparisons

models:
  openai:
    default: "gpt-4o-mini"
    alternatives:
      - "gpt-4o"
      - "gpt-4-turbo"
      - "gpt-3.5-turbo"
  
  anthropic:
    default: "claude-3-5-sonnet-20241022"
    alternatives:
      - "claude-3-5-haiku-20241022"
      - "claude-3-opus-20240229"
      - "claude-3-sonnet-20240229"
      - "claude-3-haiku-20240307"
  
  xai:
    default: "grok-3"
    alternatives:
      - "grok-2"
      - "grok-beta"
  
  google:
    default: "gemini-2.0-flash-exp"
    alternatives:
      - "gemini-2.0-flash-thinking-exp-01-21"
      - "gemini-1.5-pro"
      - "gemini-1.5-flash"
      - "gemini-1.0-pro"
  
  strands:
    # Strands uses model names without version numbers
    default: "claude-3-5-sonnet"
    alternatives:
      - "gpt-4"
      - "gpt-3.5-turbo"

# Additional configuration for agent framework comparison
comparison:
  # Number of runs per framework for averaging results
  runs_per_framework: 3
  
  # Timeout in seconds for each API call
  timeout: 30
  
  # Results output directory
  results_path: "src/notebooks/"